CREATE TABLE ai
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    species     VARCHAR(255),
    startingLevel INTEGER                                 NOT NULL,
    specialAbility VARCHAR(255),                          NOT NULL,
    bio            VARCHAR(255),
    creationDate   DAte CHECK(date <= CURRENT_DATE)
    CONSTRAINT pk_ai PRIMARY KEY (id)
);